// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropiedadesMagicas_API.Datos;

#nullable disable

namespace PropiedadesMagicas_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720022532_AlimentarTablaPropiedades")]
    partial class AlimentarTablaPropiedades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropiedadesMagicas_API.Models.Propiedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Propiedades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalles = "Detalle de Propiedad Real...",
                            FechaActualizacion = new DateTime(2023, 7, 19, 23, 25, 32, 664, DateTimeKind.Local).AddTicks(8883),
                            FechaCreacion = new DateTime(2023, 7, 19, 23, 25, 32, 664, DateTimeKind.Local).AddTicks(8876),
                            ImagenUrl = "",
                            MetrosCuadrados = 90,
                            Nombre = "Propiedad Real",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalles = "Detalle de Propiedad Barca...",
                            FechaActualizacion = new DateTime(2023, 7, 19, 23, 25, 32, 664, DateTimeKind.Local).AddTicks(8887),
                            FechaCreacion = new DateTime(2023, 7, 19, 23, 25, 32, 664, DateTimeKind.Local).AddTicks(8886),
                            ImagenUrl = "",
                            MetrosCuadrados = 30,
                            Nombre = "Propiedad Barca",
                            Ocupantes = 3,
                            Tarifa = 120.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
